### DISCUSSION TITLE
Considerations if not using cloudflare for dns or cloudflared

### DISCUSSION THREAD

**Discussion by onedr0p** [onedr0p/cluster-template#1017] [Show and tell]
As it goes with Github, using cloudflare is also requirement for using this template. This is done to streamline the template without adding a ton of options to confuse people.

However with that said it is possible to use another DNS provider or not use Cloudflare Tunnels. Because there are so many options this isn't a guide on how to implement the DNS provider of your choosing but more of a rough overview of how it can be done.

All of this is assuming you have gone thru the steps in the README right up until running `task configure`

## Using Cloudflare DNS but removing Cloudflare Tunnels

This is the easiest method to do, it means your domain's DNS needs to be managed by Cloudflare. That can be done by updating the nameservers on your current DNS provider or transferring your domain to Cloudflare.

1. Remove the Ansible verification steps for Cloudflare Tunnels in `./bootstrap/tasks/validation/cloudflare.yaml`
2. Remove the check for the cloudflared CLI tool in `./bootstrap/tasks/validation/cli.yaml`
3. Remove the cloudflared directory in `./bootstrap/templates/kubernetes/apps/networking`
4. Update `./bootstrap/templates/kubernetes/apps/networking/kustomization.yaml.j2` and remove the line containing `cloudflared`
5. Remove the cloudflared dependency in `./bootstrap/templates/kubernetes/apps/networking/nginx/external/helmrelease.yaml.j2`
6. If you wish to not have Cloudflare Proxy requests to your applications remove the line containing `--cloudflare-proxied` in `./bootstrap/templates/kubernetes/apps/networking/external-dns/app/helmrelease.yaml.j2`
7. Create a DNSEndpoint and put it in `./bootstrap/templates/kubernetes/apps/networking/nginx/external/dnsendpoint.yaml`
    ```yaml
	---
	apiVersion: externaldns.k8s.io/v1alpha1
	kind: DNSEndpoint
	metadata:
	  name: home
	  namespace: networking
	spec:
	  endpoints:
	    - dnsName: "external.${SECRET_DOMAIN}"
	      recordType: CNAME
	      targets: ["ingress.${SECRET_DOMAIN}"]
    ```
8. Add that filename to the `./bootstrap/templates/kubernetes/apps/networking/nginx/external/kustomization.yaml` resources values
9. Run `task configure` and continue where that left off in the README.
10. Create an `A` record in Cloudflare DNS pointing to your home IP address call `ingress`, make sure you have a way to update this record if you have a dynamic IP.
