### DISCUSSION TITLE
Tunnel TCP traffic through cloudflared?

### DISCUSSION THREAD

**Discussion by giannoug** [onedr0p/cluster-template#1093] [Q&A] [answered]
I'm still figuring out things and just ported (a simple version) of [traccar on my cluster](https://github.com/giannoug/azazel/commit/4ce81f5f9a66f7a45c16ca1649504e46b97878b1). Any ideas how can I access the [TCP ports needed](https://github.com/giannoug/azazel/commit/4ce81f5f9a66f7a45c16ca1649504e46b97878b1#diff-96157728eab7d7518acead05fbe81af0a28ffe6da947723db0dc9fdd9b51d5e6R51) outside my network? For example some GPS trackers require IP/port combo.

With a quick Google search I can see this is possible, but testing with the traccar Android app and my hostname doesn't seem to work. Of course, ingress is working fine and I can access the web UI

**Comment by giannoug** [comment]
I can see a config.yaml that has some cloudflared configuration with the following contents:

```
---
originRequest:
  http2Origin: true

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN}"
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN}"
  - service: http_status:404
```

The easiest guess is that I need to define my service here and it "should" work (unless I need to change more configs)
