### DISCUSSION TITLE
Adding talos support

### DISCUSSION THREAD

**Discussion by wasurerarenai** [onedr0p/cluster-template#1251] [General]
Thank you @onedr0p for adding initial talos support to the template repository.

Running through the install procedure testing I ran into a few unexpected issues. I'm working on resolving these in [my fork](https://github.com/Wasurerarenai/flux-cluster-template/tree/Wasurerarenai-talos-patches) and expect to have a PR available soon.

1. The [configure](https://github.com/onedr0p/flux-cluster-template/blob/main/Taskfile.yaml#L54-L61) task [requires](https://github.com/onedr0p/flux-cluster-template/blob/main/bootstrap/scripts/validation.py#L61-L62) a username be defined for nodes in `config.yaml` but talos doesn't allow authenticating as an OS level user. This should likely be updated to remove the username check for repositories configured for the Talos distribution.
2. The [configure](https://github.com/onedr0p/flux-cluster-template/blob/main/Taskfile.yaml#L54-L61) task [requires](https://github.com/onedr0p/flux-cluster-template/blob/main/bootstrap/scripts/validation.py#L63-L64) a diskSerial value be defined nodes in `config.yaml` but not all disks provide one at `/sys/block/<dev>/serial` (from Talos [docs](https://www.talos.dev/v1.6/reference/configuration/v1alpha1/config/#Config.machine.install.diskSelector)).
3. The [talconfig.yaml.j2](https://github.com/onedr0p/flux-cluster-template/blob/main/bootstrap/templates/kubernetes/talos/talconfig.yaml.j2#L28-L29) file disables DHCP, but doesn't set a static IP assignment. This was preventing the "vip" address from being used for me.
4. The [talconfig.yaml.j2](https://github.com/onedr0p/flux-cluster-template/blob/main/bootstrap/templates/kubernetes/talos/talconfig.yaml.j2#L32) assumes we are not using [Predictable Interface Names](https://www.talos.dev/v1.6/talos-guides/network/predictable-interface-names/) and should be adding the `net.ifnames=0` kernel argument. This can be set by talhelper in a [schematic](https://budimanjojo.github.io/talhelper/latest/reference/configuration/#schematic) with `controlPlane.schematic.customization.extraKernelArgs: - net.ifnames=0` but not sure how portable this would be.
5. The [talos:kubeconfig](https://github.com/onedr0p/flux-cluster-template/blob/main/.taskfiles/Talos/Taskfile.yaml#L45-L50) task fails with a `nodes are not set for the command: please use `--nodes` flag or configuration file to set the nodes to run the command against` error.
6. The [talos:apply-extras](https://github.com/onedr0p/flux-cluster-template/blob/main/.taskfiles/Talos/Taskfile.yaml#L51-L58) task fails with `error: must build at directory: not a valid directory: evalsymlink failure on './cni' : lstat <path/to/repo>/kubernetes/talos/cni: no such file or directory` and `error: no objects passed to apply` errors.

**Comment by wasurerarenai** [comment]
To resolve 2. I created the following two commits to add a "diskDevice" variable for nodes meant to pass a `/dev/sda` or similar to the "installDisk" talconfig.yaml setting. This was needed in my testing when I found disks not exposing a serial number for an attached disk. This was found in Proxmox Qemu VMs and one Intel NUC5 on-metal host install.

https://github.com/Wasurerarenai/flux-cluster-template/commit/1dc1fe3ec32ebe3d07827de1bbcab430a5698bed
https://github.com/Wasurerarenai/flux-cluster-template/commit/3fbdb34481fdc2fa487e789c17fc7d9385693416

**Reply by onedr0p** [reply]
This is about the amount of issues I think people would have encountered since I was pretty much shooting from the hip on adding support for Talos. Thanks for the feedback and I'll be very grateful seeing a PR come in with changes to address them 👍🏼

**Reply by onedr0p** [reply]
Maybe the nodes need a talos section? e.g.

```yaml
bootstrap_nodes:
  # Use only 1, 3 or more odd master nodes, recommended is 3
  master:
    # - name:       # name or hostname of the master node (must match [a-z0-9-\.]+)
    #   address:    # ip address of the master node
    #   username:   # ssh username of the master node (omit for talos)
    #   talos:
    #     diskDevice: # device, or
    #     # diskSerial: # serial
    # ...
```

**Reply by wasurerarenai** [reply]
Would be nice to be able to drop other Talos node-specific yaml under the `talos:` key. Looking to extend the `talconfig.yaml.j2` file with something that can drop a `item.talos.nodes_yaml` or similar block into the talconfig.yaml nodes equivalent section. Doesn't look like `to_yaml` is usable here from testing.
```
bootstrap_nodes:
  # Use only 1, 3 or more odd master nodes, recommended is 3
  master:
    - name: talos-1
      talos:
        nodes_yaml:
...
          schematic:
            customization:
              extraKernelArgs:
                - net.ifnames=0
```
can translate to:
```
nodes:
  - hostname: "talos-1"
...
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
```

**Reply by wasurerarenai** [reply]
The `controlPlane:` and `workers:` sections may also be extended without overwriting via reapplying the `task configure` task. Following https://github.com/budimanjojo/talhelper/blob/master/example/talconfig.yaml#L134 we can add a `talconfig-controlPlane-patches.yaml` and `talconfig-worker-patches.yaml` (or similarly named/stored in a patches directory) inclusion.
```
controlPlane:
  patches:
...
    - "@./talconfig-controlPlane-patches.yaml"
worker:
  patches:
...
    - "@./talconfig-worker-patches.yaml"
```

**Reply by wasurerarenai** [reply]
After the config refactor, I've added talos node-specific YAML processing with a simple block read. Since this is custom for the user, not much validation is needed from the template repo's scripts. The block was the simplest without needing to add a `to_yaml` or similar function for the jinja templating. I'll be submitting a PR for this one.
```
      - name: "talos-1"
...
        talos_disk_device: "/dev/sda"
        talos_node_config: |-
          schematic:
            customization:
              systemExtensions:
                officialExtensions:
                  - siderolabs/intel-ucode
```
https://github.com/Wasurerarenai/cluster-template/commit/593856eebd39c90ac4858e2dfe9dcc506c7ab539
https://github.com/Wasurerarenai/cluster-template/commit/ebeb3d0d3c3e2d84767a1549fba6ee502f81ae4b
