### DISCUSSION TITLE
task configure - failing and I am not sure how to troubleshoot

### DISCUSSION THREAD

**Discussion by jsaveker** [onedr0p/cluster-template#1364] [Q&A] [answered]
Hey folks....

I am standing up a new cluster but getting stuck on "task configure"

I have checked the config.yaml very carefully but am not sure how to troubleshoot.

File "/home/[redacted]/[redacted]/.venv/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/[redacted]/[redacted]/config.yaml", line 8, column 1
expected <block end>, but found '<block sequence start>'
  in "/home/[redacted]/[redacted]/config.yaml", line 23, column 6
task: Failed to run task "configure": exit status 1

Line 8 in my config is:
bootstrap_timezone: "America/New_York"

Line 6 is:
     - name: "[redacted]"

**Comment by onedr0p** [comment]
Can you share your full `config.yaml` and mask the secrets?

My first guess is you have it malformed or incorrectly configured.

**Comment by jsaveker** [comment]
My apologies for my late response...  I have attached the file.  I am seeing a parsing error on the line below bootstrap_node_inventory - a block sequence may not be used as an implicit key map.
[config.yaml.redacted.txt](https://github.com/onedr0p/cluster-template/files/14839077/config.yaml.redacted.txt)

**Comment by onedr0p** [comment, marked as answer]
```yaml
bootstrap_node_inventory: [1]
  - name: "redacted"
    address: "redacted"
    controller: true
    ssh_user: "redacted"
```

is not valid YAML, it should look like this: 

```yaml
bootstrap_node_inventory:
  - name: "redacted"
    address: "redacted"
    controller: true
    ssh_user: "redacted"
```
