### DISCUSSION TITLE
config.yaml and TunnelSecret

### DISCUSSION THREAD

**Discussion by aamoroso** [onedr0p/cluster-template#1429] [Q&A] [answered]
Hi,

Sorry if this is a dumb question or already answered (I did search but couldn't find anything).

I've got Cloudflare Zero Trust setup with a tunnel, and a cloudflared container running and that all seems good and happy.  Under the tunnel stanza of `config.yml` is the following:

```
    # (Required: CLI) Cloudflared Tunnel Secret: (cat ~/.cloudflared/*.json | jq -r .TunnelSecret)
    secret: ""
```

I can't seem to find this.  If I look in the container's file system I can't see any json files.  There is a `/home/nonroot` folder, but it is empty.

For example if I look like this:

`docker export cloudflaretunnel | tar t`

Am I blind or silly?  Im sure it's a yes to both :)

Thanks for reading this far!

Cheers,
Adrian

**Comment by onedr0p** [comment]
Did you set this up with the devcontainer? If so the home directory isn't bind mounted to your host work station.

**Reply by aamoroso** [reply]
No I couldnt seem to get that to work so did it manually

**Reply by aamoroso** [reply]
I guess my question is, how can I get this TunnelSecret value from a running container?  I can't exec into bash in the container and looking at its filesystem I can't find any json files in there.  I ran the container via docker-compose like this:

```
version: '3.9'

networks:
  app_net:                        # Defined externally (ie previously by me)
    external: true
    name: ${CONTAINER_NETWORK}

services:
  cloudflaretunnel:
    container_name: cloudflaretunnel-amoroso
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
      # - ${CONFIG_PATH}:/home/nonroot/.cloudflared/
      # - ${CONFIG_PATH}:/etc/cloudflared
    networks:
      app_net:
        ipv4_address: ${CONTAINER_IPADDR}
```
