### DISCUSSION TITLE
Is this patch missing permissions setting? talos/patches/global/machine-files.yaml

### DISCUSSION THREAD

**Discussion by rishid** [onedr0p/cluster-template#1813] [General]
Hi,

Using main HEAD branch without any changes. Just generated my talos machine configs and was reviewing them. Is the permissions `0o0` intentional? This seems wrong to me.

```
files:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
      permissions: 0o0
      path: /etc/cri/conf.d/20-customization.part
      op: create
```
