### DISCUSSION TITLE
Update Cilium BGP from the legacy configuration to the new v2 configuration

### DISCUSSION THREAD

**Discussion by snoopy82481** [onedr0p/cluster-template#1855] [Ideas]
Cilium has a new v2 configuration for the BGP deployment. Per [BGP Control Plane Resources](https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane-v2/) the `CiliumBGPPeeringPolicy` is now depreciated and cilium is saying to use the new `BGP API`.  The `networks.yaml.j2` configuration would need to be updated to the following:

```yaml
#% if cilium_bgp_enabled %#
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpclusterconfig_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: instance-#{ cilium_bgp_router_asn }#
      localASN: #{ cilium_bgp_router_asn }#
      peers:
        - name: peer-#{ cilium_bgp_node_asn }#-udmp-v4
          peerASN: #{ cilium_bgp_node_asn }#
          peerAddress: #{ cilium_bgp_router_addr }#
          peerConfigRef:
            name: cilium-peer-v4
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgppeerconfig_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-v4
spec:
  timers:
    keepAliveTimeSeconds: 3
    holdTimeSeconds: 9
    connectRetryTimeSeconds: 12
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchExpressions:
          - key: advertise
            operator: In
            values:
              - bgp
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpadvertisement_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-services
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: thisFakeSelector
            operator: NotIn
            values:
              - never-used-value
#% endif %#
```
