### DISCUSSION TITLE
Choosing a specific NIC when there are multiple NICs with calico and kube-vip

### DISCUSSION THREAD

**Discussion by onedr0p** [onedr0p/cluster-template#590] [Q&A] [answered]
# Details

This is advanced configuration but I figured it would be worth opening an issue to inform people how to deal with situations where your nodes have multiple active NICs and you want to choose which one Kubernetes uses.

**If you nodes have different network interface names, it's advised to make the names consistent across devices. Review [this](https://askubuntu.com/a/1317043) question on AskUbuntu on how to make that happen.**

These changes should be made prior to running `task configure` in the guide.

## Calico

By default, attaches to the first available internet interface (https://projectcalico.docs.tigera.io/networking/ip-autodetection).

The way around this could be achieved by setting a interface name regex in the Calico `Installation` resource.

```yaml
# ./provision/ansible/playbooks/templates/calico-installation.yaml.j2
---
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: "eno.*"
...
```

## kube-vip

By default kube-vip choose the NIC with the default gateway. To assign a specific NIC update the configuration below.

```yaml
# ./provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2
...
          env:
...
            - name: vip_interface
              value: "eno1"
...
```

```yaml
# ./tmpl/cluster/kube-vip-daemonset.yaml
...
          env:
...
            - name: vip_interface
              value: "eno1"
...
```

**Comment by brettinternet** [comment, marked as answer]
Perhaps we could automate this with Ansible using the CIDR for IP detection? https://projectcalico.docs.tigera.io/networking/ip-autodetection

```yaml
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      cidrs:
        - "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}" # 192.168.200.0/24
```
