### DISCUSSION TITLE
Ansible:ping fails

### DISCUSSION THREAD

**Discussion by tomsnj** [onedr0p/cluster-template#687] [Q&A] [answered]
It looks like ansible:ping is trying to set the user as root on the nodes when it runs based on the auth.log.  I'm running Ubuntu 22.04 LTS.  Do I need to add root to //etc//sudoers?  I have no problems up until this point in the procedure.

**Comment by onedr0p** [comment, marked as answer]
I am not sure why this isn't working for you but you can force ansible to try and ping via your user...

https://github.com/onedr0p/flux-cluster-template/blob/main/.taskfiles/AnsibleTasks.yml#L48-L52

Change to something like

```yaml
  ping:
    desc: Ping all the hosts
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible all -i {{.ANSIBLE_INVENTORY_DIR}}/hosts.yml -u YOURUSERNAME --one-line -m 'ping'
```

The user should be picked up from your vars but in your case it is unable to.
