### DISCUSSION TITLE
Where does node role "worker" get set?

### DISCUSSION THREAD

**Discussion by adampetrovic** [onedr0p/cluster-template#792] [Q&A] [answered]
I've noticed in your README that your worker nodes get a role of "worker" applied

For example:
```
task cluster:nodes
# NAME           STATUS   ROLES                       AGE     VERSION
# k8s-0          Ready    control-plane,master      4d20h   v1.21.5+k3s1
# k8s-1          Ready    worker                    4d20h   v1.21.5+k3s1
```

However my worker nodes all have `<none>` set as their role, meaning I can't set worker node pod affinity using a nodeSelector

my hosts.yaml
```
---
kubernetes:
  children:
    master:
      hosts:
        k8s-node-1:
          ansible_host: 10.0.80.1
        k8s-node-6:
          ansible_host: 10.0.80.6
        k8s-node-7:
          ansible_host: 10.0.80.7
    worker:
      hosts:
        k8s-node-2:
          ansible_host: 10.0.80.2
        k8s-node-3:
          ansible_host: 10.0.80.3
        k8s-node-4:
          ansible_host: 10.0.80.4
        k8s-node-5:
          ansible_host: 10.0.80.5
```

my node roles:
```
NAME         STATUS   ROLES                       AGE    VERSION
k8s-node-1   Ready    control-plane,etcd,master   10d    v1.27.2+k3s1
k8s-node-2   Ready    <none>                      10d    v1.27.2+k3s1
k8s-node-3   Ready    <none>                      10d    v1.27.2+k3s1
k8s-node-4   Ready    <none>                      10d    v1.27.2+k3s1
k8s-node-5   Ready    <none>                      10d    v1.27.2+k3s1
k8s-node-6   Ready    control-plane,etcd,master   117m   v1.27.2+k3s1
k8s-node-7   Ready    control-plane,etcd,master   116m   v1.27.2+k3s1
```

Where is this meant to be set?

**Comment by onedr0p** [comment, marked as answer]
I've converted this into a discussion...

This is to be set manually after the cluster is deployed. I've tried many times to have k3s set this label during bootstrap using the Ansible k3s role however there's some weird bug that prevents the k3s service from starting if that config is set.

It's been about a year since I last tried so feel free to try this again and open a PR if you discover it works.

---

Edit:

https://github.com/onedr0p/flux-cluster-template/blob/main/ansible/inventory/group_vars/worker/k3s.yml

```yaml
---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: false
k3s_agent:
  node-ip: "{{ ansible_host }}"
  node-label:
    - "node-role.kubernetes.io/worker=worker" # Will not work, see below
```

This won't work, read here: https://github.com/k3s-io/k3s/issues/1289

Looks like this is the reason you cannot do it the above way...

https://github.com/rancher/rke2/issues/3730#issuecomment-1368077700
