### ISSUE TITLE
hajimari PVC missing namespace

### ISSUE THREAD

**Issue by PrymalInstynct** [onedr0p/cluster-template#118]
# Details

**What steps did you take and what happened:**

When using the default template the hajimari helm release fails to install because there is not a namespace defined for the PersistentVolumeClaim
```
flux get kustomizations -A
NAMESPACE       NAME            READY   MESSAGE                                                                                                                 REVISION                                                SUSPENDED 
flux-system     apps            False   PersistentVolumeClaim/hajimari-config namespace not specified, error: the server could not find the requested resource
```

**What did you expect to happen:**

I expected the hajimari helm release to be installed and start

**Anything else you would like to add:**

Updated cluster/apps/default/hajimari/config-pvc.yaml

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi

```

**Additional Information:**

I would personally like to see this app in a namespace other then default.
