### ISSUE TITLE
Talos install error:  "failed to verify certificate: x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by bojanraic** [onedr0p/cluster-template#1398]
Used the template with k3s and I liked the setup for the most part, but I wanted to try Talos, just for comparison. 
Trying a Talos 1.6.7 install. Can't figure out why I'm getting a cert error. I ran talos bootstrap tasks individually and  it seems fine until the install step, where I get 
`error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"`
Maybe I missed something so any pointers would be very welcome. Thanks!

**Comment by onedr0p** [comment]
I have seen other people report this issue but never found the root cause. It appears to be related to their workstation environment. Are you able to post your `config.yaml` and the rendered `talhelper.yaml`? Maybe something in there can shed some light on why this is happening for some people and not others.

**Comment by bojanraic** [comment]
Hey, thanks for the quick reply, appreciate it. 
Hmmm, very possible that it is indeed related to local setup. I'll try a few more things, including a clean devcontainer approach and will post back later today or tomorrow.

**Comment by DavidIlie** [comment]
It seems that the "--insecure" is not being appended, as in the `config.yaml` in the guidance to fetch information from the particular nodes, you need to append the "--insecure" flag for it to work, and I am having the same issue right now.

**Comment by DavidIlie** [comment]
![image](https://github.com/onedr0p/cluster-template/assets/47594764/2a1db561-c877-4a7e-91cf-84a734b463cb)

config.yaml
```
---
bootstrap_timezone: "Europe/Bucharest"

bootstrap_distribution: talos

bootstrap_cluster_name: "davidapps"

bootstrap_talos:
  schematic_id: ""
  vlan: ""
  secureboot:
    enabled: false
    encrypt_disk_with_tpm: false
  user_patches: false

bootstrap_node_network: "192.168.100.0/24"

bootstrap_node_default_gateway: "192.168.100.1"

bootstrap_node_inventory:
  - name: "master-01"
    address: ""
    controller: true
    talos_disk: "/dev/sda"
    talos_nic: ""
    ssh_user: "david"
  - name: "master-02"
    address: ""
    controller: true
    talos_disk: "/dev/sda"
    talos_nic: ""
    ssh_user: "david"
  - name: "master-03"
    address: ""
    controller: true
    talos_disk: "/dev/vda"
    talos_nic: ""
    ssh_user: "david"
  - name: "worker-01"
    address: ""
    controller: false
    talos_disk: "/dev/sda"
    talos_nic: ""
    ssh_user: "david"
  - name: "worker-02"
    address: ""
    controller: false
    talos_disk: "/dev/sda"
    talos_nic: ""
    ssh_user: "david"
  - name: "worker-03"
    address: ""
    controller: false
    talos_disk: "/dev/vda"
    talos_nic: ""
    ssh_user: "david"

bootstrap_dns_servers: ["192.168.100.1", "8.8.8.8"]

bootstrap_search_domain: ""

bootstrap_pod_network: "10.69.0.0/16"

bootstrap_service_network: "10.96.0.0/16"

bootstrap_controllers_vip: "192.168.100.169"

bootstrap_tls_sans: []

bootstrap_sops_age_pubkey: ""

bootstrap_github_address: "https://github.com/davidilie/home-cluster"

bootstrap_github_branch: "main"

bootstrap_github_webhook_token: ""

bootstrap_github_private_key: |


bootstrap_cloudflare:
  enabled: true
  domain: "https://davidapps.dev"
  token: ""
  acme:
    email: "david@davidapps.dev"
    production: true
  ingress_vip: "192.168.100.102"
  gateway_vip: "192.168.100.100"
  tunnel:
    id: ""
    account_id: ""
    secret: ""
    ingress_vip: ""
```

talconfig.yaml
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.7
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.3

clusterName: &cluster davidapps
endpoint: https://192.168.100.169:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"
additionalApiServerCertSans: &sans
  - "192.168.100.169"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans
cniConfig:
  name: none

nodes:
  - hostname: "master-01"
    ipAddress: "192.168.100.53"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.53/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"
        vip:
          ip: "192.168.100.169"
  - hostname: "master-02"
    ipAddress: "192.168.100.57"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.57/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"
        vip:
          ip: "192.168.100.169"
  - hostname: "master-03"
    ipAddress: "192.168.100.54"
    installDisk: "/dev/vda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.54/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"
        vip:
          ip: "192.168.100.169"
  - hostname: "worker-01"
    ipAddress: "192.168.100.58"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.58/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"
  - hostname: "worker-02"
    ipAddress: "192.168.100.59"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.59/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"
  - hostname: "worker-03"
    ipAddress: "192.168.100.55"
    installDisk: "/dev/vda"
    talosImageURL: factory.talos.dev/installer/
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: ""
        dhcp: false
        addresses:
          - "192.168.100.55/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.100.1"

patches:
  # Configure containerd
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |-
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              discard_unpacked_layers = false

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Enable cluster discovery
  - |-
    cluster:
      discovery:
        registries:
          kubernetes:
            disabled: false
          service:
            disabled: false

  # Configure kubelet
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: true
        nodeIP:
          validSubnets: ["192.168.100.0/24"]

  # Force nameserver
  - |-
    machine:
      network:
        nameservers:
          - 192.168.100.1
          - 8.8.8.8

  # Configure NTP
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

  # Custom sysctl settings
  - |-
    machine:
      sysctls:
        fs.inotify.max_queued_events: 65536
        fs.inotify.max_user_watches: 524288
        fs.inotify.max_user_instances: 8192

  # Mount openebs-hostpath in kubelet
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options: ["bind", "rshared", "rw"]



controlPlane:
  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - "192.168.100.0/24"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles: ["os:admin"]
            allowedKubernetesNamespaces: ["system-upgrade"]
```
