### ISSUE TITLE
add support for busPath in node config

### ISSUE THREAD

**Issue by brunnels** [onedr0p/cluster-template#1512]
Some machines are stupid and change the order of the disks around depending on what you booted from so using `busPath` lets you ensure you're targeting the disk you want.

talhelper accepts [`installDiskSelector`](https://budimanjojo.github.io/talhelper/latest/reference/configuration/#installdiskselector) which fully replaces `disk`. 

Desired config example

```yaml
bootstrap_node_inventory:
  - name: "tc1"
    address: "10.50.0.19"
    controller: true
    busPath: "/pci0000:00/0000:00:08.2/0000:0e:00.0/ata10/host10/target10:0:0/10:0:0:0/"
    mac_addr: "1c:86:0b:27:14:2b"
```
