### ISSUE TITLE
Duplicate scheduler configs

### ISSUE THREAD

**Issue by insuusvenerati** [onedr0p/cluster-template#1647]
Hi there! I always use your template so thank you. On a fresh repo it looks like a second scheduler profile is being created for some reason and I can't seem to track down why. 

```yaml
      profiles:
        - pluginConfig:
            - args:
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                defaultingType: List
              name: PodTopologySpread
          schedulerName: default-scheduler
        - pluginConfig:
            - args:
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                defaultingType: List
              name: PodTopologySpread
          schedulerName: default-scheduler
```
Any ideas?
