### ISSUE TITLE
There is an attempt at refactoring the `config.yaml`

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/cluster-template#1697]
I've been trying to come up with better organization of options, it's still a single file but I split up the config into sections. Any feedback would be appreciated. I hope to use cue for most validation if it's not a huge burden

## cilium

```yaml
cilium:
  bgp:
    enabled: false
    node_asn: 64514
    router_address: ""
    router_asn: 64513
  loadbalancer_mode: "dsr"
```

## cluster

```yaml
cluster:
  api:
    address: ""
    sans: []
  default_gateway: ""
  dns_servers: []
  encryption:
    age_public_key: ""
  node_cidr: ""
  nodes: []
  ntp_servers: []
  networks:
    pod_cidr: ""
    service_cidr: ""
  vlan: -1
```

## external_services

```yaml
external_services:
  cloudflare:
    enabled: false
    api_token: ""
    domain: ""
    letsencrypt_production: false
    tunnel_ingress_address: ""
  dns_address: ""
  ingress_address: ""
```

## github

```yaml
github:
  repository: ""
  branch: "main"
  push_token: ""
  private: false

```

## experimental

```yaml
experimental:
  dual_stack_ipv4_first: false
```
