### ISSUE TITLE
No way to load kernel modules

### ISSUE THREAD

**Issue by Yornik** [onedr0p/cluster-template#1778]
when using the zfs and iscsi extendions you need to[ add ](https://github.com/Yornik/homo-home-lab/commit/8f7da730ad60f8ed22fed1fbf5fad44f7ed63b42) this manualy to the talhelper config file

```
    kernelModules: 
      - name: zfs
      - name: iscsi_tcp
      - name: libiscsi
      - name: libiscsi_tcp
```

Or am i missing something important.

So if i change the config.yaml e.g to use LE production server it breaks again.
